# Generated by Django 3.2 on 2021-04-13 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('initial_date', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('time_executated_start', models.FloatField()),
                ('time_executated_end', models.FloatField()),
                ('time_executation_duration', models.FloatField()),
                ('num_vehicles', models.FloatField()),
                ('num_store', models.FloatField()),
                ('num_circuit', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
